# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'seguridad-upr' do

end

target 'seguridad-uprTests' do

end

